INSERT INTO `municipio` VALUES (1, 'Abasolo');
INSERT INTO `municipio` VALUES (2, 'Acuña');
INSERT INTO `municipio` VALUES (3, ' Allende');
INSERT INTO `municipio` VALUES (4, ' Arteaga');
INSERT INTO `municipio` VALUES (5, ' Candela');
INSERT INTO `municipio` VALUES (6, ' Castaños');
INSERT INTO `municipio` VALUES (7, ' Cuatro Cienegas');
INSERT INTO `municipio` VALUES (8, ' Escobedo');
INSERT INTO `municipio` VALUES (9, ' Francisco I. Madero');
INSERT INTO `municipio` VALUES (10, ' Frontera');
INSERT INTO `municipio` VALUES (11, ' General Cepeda');
INSERT INTO `municipio` VALUES (12, ' Guerrero');
INSERT INTO `municipio` VALUES (13, ' Hidalgo');
INSERT INTO `municipio` VALUES (14, ' Jiménez');
INSERT INTO `municipio` VALUES (15, ' Juárez ');
INSERT INTO `municipio` VALUES (16, ' Lamadrid');
INSERT INTO `municipio` VALUES (17, ' Matamoros');
INSERT INTO `municipio` VALUES (18, ' Monclova');
INSERT INTO `municipio` VALUES (19, ' Morelos');
INSERT INTO `municipio` VALUES (20, ' Múzquiz ');
INSERT INTO `municipio` VALUES (21, ' Nadadores');
INSERT INTO `municipio` VALUES (22, ' Nava');
INSERT INTO `municipio` VALUES (23, ' Ocampo');
INSERT INTO `municipio` VALUES (24, ' Parras');
INSERT INTO `municipio` VALUES (25, ' Piedras Negras');
INSERT INTO `municipio` VALUES (26, ' Progreso');
INSERT INTO `municipio` VALUES (27, ' Ramos Arizpe');
INSERT INTO `municipio` VALUES (28, ' Sabinas');
INSERT INTO `municipio` VALUES (29, ' Sacramento');
INSERT INTO `municipio` VALUES (30, 'Saltillo');
INSERT INTO `municipio` VALUES (31, ' San Buenaventura');
INSERT INTO `municipio` VALUES (32, ' San Juan de Sabinas');
INSERT INTO `municipio` VALUES (33, ' San Pedro');
INSERT INTO `municipio` VALUES (34, ' Sierra Mojada');
INSERT INTO `municipio` VALUES (35, ' Torreón');
INSERT INTO `municipio` VALUES (36, ' Viesca');
INSERT INTO `municipio` VALUES (37, ' Villa Unión');
INSERT INTO `municipio` VALUES (38, 'Zaragoza');